services:
  backend:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    working_dir: /App
    volumes:
      - ./:/App
      - /App/obj/
      - /App/bin/
    ports:
      - "8080:8080"
    command: dotnet watch run --urls=http://+:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=database;Database=thiskord;User Id=sa;Password=MonSuperMotDePasse123!;TrustServerCertificate=True;
    depends_on:
      - database 
    networks:
      - backend_network

  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MonSuperMotDePasse123!
    volumes:  
      - database_data:/var/opt/mssql
    ports:
      - "1433:1433"
    networks:
      - backend_network
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P MonSuperMotDePasse123! -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s

volumes:
  database_data:

networks:
  backend_network:
    driver: bridge