services:
  backend:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    working_dir: /App
    volumes:
      - ./:/App
      - /App/obj/
      - /App/bin/
    ports:
      - "8080:8080"
    command: dotnet watch run --urls=http://+:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

